#+TITLE: Coding Python

Does a literate-ish emacs document make a good place to learn python and develop the re-usable pieces I want for parsing lectionary data? Let's see.

* Reference
- [[https://linuxhint.com/configuring_emacs_python/][Configure like so]]
- [[https://orgmode.org/worg/org-contrib/babel/intro.html][Introduction to Babel]]
- Use C-c ' within the code block to edit
- Use C-c C-p within the editor to run it
- [[https://docs.python.org/3.9/][Python Doc's]]
- [[https://linuxhint.com/python_scripts_beginners_guide/][Python examples]]
- In interactive python, =dir(cmd)= is a great boon!
** Use python3
#+BEGIN_SRC bash
python3 --version
#+END_SRC

#+RESULTS:
: Python 3.9.1

#+BEGIN_SRC python :results output
  print ("Hello world!")
#+END_SRC

#+RESULTS:
: Hello world!

#+BEGIN_SRC python :results output
  import sys
  print (sys.version)
#+END_SRC

#+RESULTS:
: 2.7.16 (default, Nov 23 2020, 08:01:20)
: [GCC Apple LLVM 12.0.0 (clang-1200.0.30.4) [+internal-os, ptrauth-isa=sign+stri

#+BEGIN_SRC python :python python3 :results output
  import sys
  print (sys.version)
#+END_SRC

#+RESULTS:
: 3.9.1 (default, Jan  8 2021, 17:17:43)
: [Clang 12.0.0 (clang-1200.0.32.28)]
** Take a filename as input -- doesn't seem to work in babel?
#+BEGIN_SRC python :python python3 :results output :cmdline "a, b, c, 42"
import sys
if __name__ == "__main__":
    print(f"Arguments count: {len(sys.argv)}")
    for i, arg in enumerate(sys.argv):
        print(f"Argument {i:>6}: {arg}")
#+END_SRC

#+RESULTS:
: Arguments count: 1
: Argument      0:

** Traverse a text file
#+BEGIN_SRC python :python python3 :results output
  with open("collects.csv", "r") as f:
      for line in f:
          if (line[1:7]=="advent"):
              print (line[1:8])
#+END_SRC

#+RESULTS:
: advent1
: advent2
: advent3
: advent4

** Use the csv library
#+BEGIN_SRC python :python python3 :results output
  import csv
  with open("collects.csv", "r") as f:
      reader = csv.reader(f)
      for row in reader:
          if len(row[0])>0:
              print(row[0])
#+END_SRC

#+RESULTS:
#+begin_example
Code
advent1
advent2
advent3
advent4
nativity1
nativity2
nativity3
christmas1
holyname
christmas2
epiphany
epiphany1
epiphany2
epiphany3
epiphany4
presentation
epiphany5
epiphany6
epiphany7
epiphany8
epiphanylast
ashwednesday
lent1
lent2
lent3
lent4
lent5
annunciation
palmsunday
holymonday
holytuesday
holywednesday
maundythursday
goodfriday
holysaturday
vigil
easter
easterevening
eastermonday
eastertuesday
easterwednesday
easterthursday
easterfriday
eastersaturday
easter2
easter3
easter4
easter5
easter6
ascension
ascension-grant
easter7
pentecost-ogod
pentecost
trinity
visitation
proper1
proper2
proper3
proper4
proper5
proper6
proper7
proper8
proper9
proper10
proper11
proper12
proper13
proper14
proper15
proper16
proper17
proper18
proper19
holycross
proper20
proper21
proper22
proper23
thanksgivingcanadian
proper24
proper25
proper26
allsaints
proper27
proper28
proper29
thanksgivingusa
#+end_example

** Books of the Bible
Genesis
Exodus
Leviticus
Numbers
Deuteronomy
Joshua
Judges
Ruth
1 Samuel
2 Samuel
1 Kings
2 Kings
1 Chronicles
2 Chronicles
Ezra
Esther
Job
Psalms
Proverbs
Ecclesiastes
Song of Solomon
Isaiah
Jeremiah
Lamentations
Ezekiel
Daniel
Hosea
Joel
Amos
Obadiah
Jonah
Micah
Nahum
Habakkuk
Zephaniah
Haggai
Zechariah
Malachi
Tobit
Judith
Additions to Esther
Wisdom of Solomon
Sirach (Ecclesiasticus)
Baruch
1 Esdras
2 Esdras
Letter of Jeremiah
Prayer of Azariah and the Song of the Three Jews
Susanna
Bel and the Dragon
1 Maccabees
2 Maccabees
3 Maccabees
4 Maccabees
Prayer of Manasseh
Matthew
Mark
Luke
John
Acts of the Apostles
Romans
1 Corinthians
2 Corinthians
Galatians
Ephesians
Philippians
Colossians
1 Thessalonians
2 Thessalonians
1 Timothy
2 Timothy
Titus
Philemon
Hebrews
James
1 Peter
2 Peter
1 John
2 John
3 John
Jude
Revelation

* Output to files
** Archive
*** Produce Psalms in =readings/pss/plaintext=
Format:
  - Blank line between Psalms/parts
  - # Psalm number (filename)
  - ## Part of Psalm or letter for Ps 119 (bold)
  - ### Latin title (italic)
  - Add "Part" to filename for those that contain the keyword
  - Psalm119: add a \n for each new letter heading

#+BEGIN_SRC python :python python3 :results output
  import os
  targetdir = "readings/pss/plaintext/"
  os.makedirs(targetdir, exist_ok=True)

  countLines = 0
  countPsalms = 0
  previousLine = ""
  with open("psalter.txt", "r") as f:
      line = f.readline().rstrip()
      while line:
          if (line[0:2] != "# "):
              print ("Unexpected input: " + line)
              break;
          # New Psalm
          countPsalms += 1
          countLines += 2
          title = line[2:]
          # Check for Part I/Part II
          line = f.readline().rstrip()
          countLines += 1
          if (title != "119" and line[0:3] == "## "):
              title = title + line[3:].replace (" ", "")
          # Open new file for writing
          with open (targetdir + "/" + title, "w") as t:
              while (len(line)>0):
                  if (line[0:3] == "## "):
                      if (title == "119" and line != "## Aleph"):
                          t.write("\n")
                      t.write(line[3:] + "\n")
                  elif (line[0:4] == "### "):
                      t.write(line[4:] + "\n")
                  else:
                      t.write(line + "\n")
                  line = f.readline().rstrip()
                  countLines += 1
          line = f.readline().rstrip()
  print ("Wrote " + str(countLines) + " lines in " + str(countPsalms) + " files.")
#+END_SRC

#+RESULTS:
: Wrote 6328 lines in 157files.
*** Produce Psalms in =readings/pss/plain=
Format:
  - Blank line between Psalms/parts
  - # Psalm number (filename)
  - ## Part of Psalm or letter for Ps 119 (bold)
  - ### Latin title (italic)
  - Add "Part" to filename for those that contain the keyword
  - Psalm119: add a \n for each new letter heading

#+BEGIN_SRC python :python python3 :results output
  import os
  targetdir = "readings/pss/plain/"
  os.makedirs(targetdir, exist_ok=True)

  countLines = 0
  countPsalms = 0
  previousLine = ""
  with open("psalter.txt", "r") as f:
      line = f.readline().rstrip()
      while line:
          if (line[0:2] != "# "):
              print ("Unexpected input: " + line)
              break;
          # New Psalm
          countPsalms += 1
          countLines += 2
          title = line[2:]
          # Check for Part I/Part II
          line = f.readline().rstrip()
          countLines += 1
          if (title != "119" and line[0:3] == "## "):
              title = title + line[3:].replace (" ", "")
          # Open new file for writing
          with open (targetdir + "/" + title, "w") as t:
              while (len(line)>0):
                  if (line[0:3] == "## "):
                      if (title == "119" and line != "## Aleph"):
                          t.write("\n")
                      t.write("**" + line[3:] + "**" + "\n")
                  elif (line[0:4] == "### "):
                      t.write("_" + line[4:] + "_" + "\n")
                  else:
                      t.write(line + "\n")
                  line = f.readline().rstrip()
                  countLines += 1
          line = f.readline().rstrip()
  print ("Wrote " + str(countLines) + " lines in " + str(countPsalms) + " files.")
#+END_SRC

#+RESULTS:
: Wrote 6328 lines in 157files.
*** Produce Psalms in =readings/pss/responsively=
Format:
  - Blank line between Psalms/parts
  - # Psalm number (filename)
  - ## Part of Psalm or letter for Ps 119 (bold)
  - ### Latin title (italic)
  - Add "Part" to filename for those that contain the keyword
  - Psalm119: add a \n for each new letter heading

#+BEGIN_SRC python :python python3 :results output
  import os
  targetdir = "readings/pss/responsively/"
  os.makedirs(targetdir, exist_ok=True)

  countLines = 1
  countPsalms = 0
  with open("psalter.txt", "r") as f:
      line = f.readline().rstrip()
      while line:
          if (line[0:2] != "# "):
              print ("Unexpected input: " + line)
              break;
          countPsalms += 1
          title = line[2:]

          # Check for Part I/Part II
          line = f.readline().rstrip()
          countLines += 1
          if (title != "119" and line[0:3] == "## "):
              title = title + line[3:].replace (" ", "")

          # Open new file for writing
          with open (targetdir + "/" + title, "w") as t:
              newPsalm = True
              responseOpen = False
              while (len(line)>0):
                  if not newPsalm:
                      t.write ("\n")
                  if (line[0:3] == "## "): # Part or Letter
                      if (title == "119"):
                          if (newPsalm):
                            t.write("_" + line[3:] + "_\n")
                          else:
                              t.write ("\n_" + line[3:] + "_")
                      else:
                          t.write("_" + line[3:] + "_\n")
                      line = f.readline().rstrip()
                  elif (line[0:4] == "### "): # latin title
                      if (title == "119"):
                          t.write("_" + line[4:] + "_\n")
                      else:
                          t.write("_" + line[4:] + "_\n\n")
                      line = f.readline().rstrip()
                  else:
                      if (line[0].isdigit()):
                          responseOpen = not newPsalm and not responseOpen
                          newPsalm = False
                          if responseOpen:
                              t.write ("> **" + line)
                          else:
                              t.write ("> " + line)
                      else:
                          t.write (line)
                      line = f.readline().rstrip()
                      countLines += 1
                      if (responseOpen and (len(line) == 0 or line[0].isdigit())):
                          t.write("**\n") # two \n's on purpose
              line = f.readline().rstrip() # Drew a blank: try for another line
  print ("Wrote " + str(countLines) + " lines in " + str(countPsalms) + " files.")
#+END_SRC

#+RESULTS:
: Wrote 5801 lines in 157 files.
*** Dump collects into directory =collects=
#+BEGIN_SRC python :python python3 :results output
  import csv, os
  targetdir = "collects"
  os.makedirs(targetdir, exist_ok=True)
  count=0
  with open("collects.csv", "r") as f:
      reader = csv.reader(f)
      for row in reader:
          if row[0] == "Code": continue # Skip header row
          if len(row[0])<3: continue   # Skip uncoded or badly coded rows
          count+=1
          with open (targetdir + "/" + row[0], "w") as t:
            t.write(row[1])
  print ("Wrote " + str(count) + " records")
#+END_SRC

#+RESULTS:
: Wrote 118 records

** Dump multiple columns into directory =proper=
Each column gets its own sub-directory. Each entry is named with the week-code. e.g., =proper/collect/epiphany3=

#+BEGIN_SRC python :python python3 :results output
  import csv, os
  targetdir = "output/proper/"
  codeColumn = 1
  fields = {
      "collect": 2,
      "preface": 3,
      "title": 4
  }

  for dir in fields.keys():
    os.makedirs(targetdir + dir, exist_ok=True)

  count=0
  with open("src/collects.csv", "r") as f:
      reader = csv.reader(f)
      next(reader) # skip header line
      for row in reader:
          if row[0] == "999": continue # Skip unused rows
          code = row[1]
          if len(code)<3: continue   # Skip uncoded or badly coded rows
          count+=1
          for dir, column in fields.items():
              with open (targetdir + dir + "/" + code, "w") as t:
                  t.write(row[column])
  print ("Wrote " + str(count) + " records for each of " + str(len(fields)) + " fields.")
#+END_SRC

#+RESULTS:
: Wrote 115 records for each of 3 fields.
** Produce books of Bible lookup in =readings/intro=
Issue:
  - Philippians and Philemon require five characters to distinguish
  - Job 1 and Job 2 should use the same entry
 This sounds like a job for a regular expression!
 I like =^..[a-z]{1,3}= but the online testers don't catch the leading numerals. Maybe the fault of the javascript implementation?
Each file is named with the first five non-space characters, in lower case.

#+BEGIN_SRC python :python python3 :results output
  import csv, os
  targetdir = "output/readings/intro/"
  codeColumn = 1
  introColumn = 2

  os.makedirs(targetdir, exist_ok=True)

  count=0
  with open("src/booksofbible.csv", "r") as f:
      reader = csv.reader(f)
      next(reader) # skip header line
      for row in reader:
          if row[0] == "": continue # Skip unused rows
          code = row[1].lower().replace(" ","")[0:5]
          count+=1
          with open (targetdir + "/" + code, "w") as t:
              t.write(row[introColumn])
  print ("Wrote " + str(count) + " records.")
#+END_SRC

#+RESULTS:
: Wrote 82 records.

** Better Psalm parser
Load each Psalm into memory at once, then format & output as needed
Format of input file:
  - Blank line between Psalms
  - # Psalm number (filename)
  - ## Part of Psalm or letter for Ps 119 (bold)
  - ### Latin title (italic)
  - When Parts/titles occur mid-Psalm, give an extra \n above it

#+BEGIN_SRC python :python python3 :results output
  import os
  targetdir_plaintext = "output/readings/pss/plaintext/"
  targetdir_markdown  = "output/readings/pss/markdown/"
  targetdir_responsively = "output/readings/pss/responsively/"
  os.makedirs(targetdir_plaintext, exist_ok=True)
  os.makedirs(targetdir_markdown, exist_ok=True)
  os.makedirs(targetdir_responsively, exist_ok=True)

  countPsalms = 0
  countLines = 0
  countFiles = 0
  with open("src/psalter.txt", "r") as f:
      line = f.readline().rstrip()
      countLines += 1
      while len(line) > 1:
          if (line[0:2] != "# "):
              print ("Unexpected input: " + line)
              break;
          countPsalms += 1
          title = line[2:]

          # Read in entire Psalm
          psalm = []
          line = f.readline()
          countLines += 1
          while len(line) > 1:
              psalm.append(line.rstrip())
              line = f.readline()
              countLines += 1

          # Output plaintext Psalm
          atTheBeginning = 2
          with open (targetdir_plaintext + "/" + title, "w") as t:
              countFiles += 1
              for l in psalm:
                  if (l[0:3] == "## "):
                      if (atTheBeginning <= 0 and l[0] == "#"):
                          t.write("\n")
                      t.write(l[3:] + "\n")
                  elif (l[0:4] == "### "):
                      t.write(l[4:] + "\n")
                  else:
                      t.write(l + "\n")
                  atTheBeginning -= 1

          # Output markdown Psalm
          atTheBeginning = 2
          with open (targetdir_markdown + "/" + title, "w") as t:
              countFiles += 1
              for l in psalm:
                  if (l[0:3] == "## "):
                      if (atTheBeginning <= 0 and l[0] == "#"):
                          t.write("\n")
                      t.write("**" + l[3:] + "**\n")
                  elif (l[0:4] == "### "):
                      t.write("_" + l[4:] + "_\n\n")
                  else:
                      l = l.replace(" *", " \\*")
                      t.write("> " + l + "  \n")
                  atTheBeginning -= 1

          # Output responsive Psalm
          foundAVerse = False
          isEven = False
          with open (targetdir_responsively + "/" + title, "w") as t:
              countFiles += 1
              for l in psalm:
                  if (foundAVerse):
                      # If not the beginnig of the Psalm, finish off the last line
                      if (isEven and (l[0].isdigit() or l[0] == "#")):
                          t.write("**  \n") # extra line between pairs
                      t.write("  \n")

                  # Process the line
                  if (l[0:3] == "## "):
                      t.write("**" + l[3:] + "**\n")
                      isEven = False
                      foundAVerse = False
                  elif (l[0:4] == "### "):
                      t.write("_" + l[4:] + "_\n\n")
                      isEven = False
                      foundAVerse = False
                  else:
                      if (l[0].isdigit()):
                          t.write("> ")
                          if (foundAVerse):
                              isEven = not isEven
                          if (isEven):
                              t.write("**")
                          foundAVerse = True
                      l = l.replace(" *", " \\*")
                      t.write(l)
              # If not the beginnig of the Psalm, finish off the last line
              if (isEven):
                  t.write("**")
              t.write("  \n")
          line = f.readline().rstrip()
          countLines += 1
  print ("Wrote " + str(countLines) + " lines in " + str(countFiles) + " files for " + str(countPsalms) + " Psalms.")
#+END_SRC

#+RESULTS:
: Wrote 6060 lines in 450 files for 150 Psalms.

** Eucharistic Lectionary
*** Parse =src/bcprcl-yearb.txt=
Format:
|-----------------------------|
| week-code                   |
| Psalm                       |
| First Reading               |
| Second Reading              |
| Gospel                      |
| Opt. Track II Psalm         |
| Opt. Track II First Reading |
| Blank Line                  |
**** Test out file format
#+BEGIN_SRC python :python python3 :results output
  import os
  srcfile = "src/bcprcl-yearb.txt"
  countRecords = 0
  with open(srcfile, "r") as f:
      weekcode = f.readline().rstrip()
      while weekcode:
          # print ("Week found: " + weekcode)
          countRecords += 1
          f.readline().rstrip()
          f.readline().rstrip()
          f.readline().rstrip()
          f.readline().rstrip()
          nextLine = f.readline().rstrip()
          if nextLine:
              altReading = f.readline().rstrip()
              # print ("Track II? "+ nextLine + " - " + altReading)
              f.readline().rstrip()
          weekcode = f.readline().rstrip()
  print ("Found " + str(countRecords) + " records")
#+END_SRC

#+RESULTS:
: Found 85 records
**** Parse out file
#+BEGIN_SRC python :python python3 :results output
  import os
  import shutil
  srcfile = "src/bcprcl-yearb.txt"
  track1 = "output/readings/yearb/track1/"
  track2 = "output/readings/yearb/track2/"
  opinionated = "output/readings/yearb/opinionated/"
  countRecords = 0
  shutil.rmtree(track1, ignore_errors=True)
  shutil.rmtree(track2, ignore_errors=True)
  shutil.rmtree(opinionated, ignore_errors=True)

  with open(srcfile, "r") as f:
      weekcode = f.readline().rstrip()
      while weekcode:
          countRecords += 1
          psalm = f.readline().rstrip()
          firstReading = f.readline().rstrip()
          secondReading = f.readline().rstrip()
          gospel = f.readline().rstrip()
          nextLine = f.readline().rstrip()
          if nextLine:
              altPsalm = nextLine
              altReading = f.readline().rstrip()
              if f.readline().rstrip():
                  raise Exception("Unexpected input near " + weekcode + ": " + nextLine)

          # Output track 1 readings
          dest = track1 + weekcode + "/"
          os.makedirs(dest, exist_ok=False)
          with open (dest + "psalm", "w") as t:
              t.write(psalm)
          with open (dest + "gospel", "w") as t:
              t.write(gospel)
          if firstReading:
              with open (dest + "firstReading", "w") as t:
                  t.write(firstReading)
          if secondReading:
              with open (dest + "secondReading", "w") as t:
                  t.write(secondReading)
          if nextLine:
              with open (dest + "track2psalm", "w") as t:
                  t.write(altPsalm)
              with open (dest + "track2Reading", "w") as t:
                  t.write(altReading)

          # Output track 2 readings
          dest = track2 + weekcode + "/"
          os.makedirs(dest, exist_ok=False)
          with open (dest + "gospel", "w") as t:
              t.write(gospel)
          if secondReading:
              with open (dest + "secondReading", "w") as t:
                  t.write(secondReading)
          if nextLine:
              with open (dest + "psalm", "w") as t:
                  t.write(altPsalm)
              with open (dest + "firstReading", "w") as t:
                  t.write(altReading)
          else:
              with open (dest + "psalm", "w") as t:
                  t.write(psalm)
              if firstReading:
                  with open (dest + "firstReading", "w") as t:
                      t.write(firstReading)


          # Output opinionated readings
          ## 1: Follow Track 1
          ## 2: if a canticle, choose second (Rite II)
          ## 3: else choose the first option ("or")
          ## 4: Easter, Pentecost: choose Heb reading, use Acts 2nd
          dest = opinionated + weekcode + "/"
          os.makedirs(dest, exist_ok=False)
          # When there are choices to be made ("or"), choose the first
          with open (dest + "psalm", "w") as t:
              if psalm.find("Canticle") == 0:
                  psalm = "Canticle " + psalm.partition(" or ")[2].lstrip()
              t.write(psalm.partition(" or ")[0])
          with open (dest + "gospel", "w") as t:
              t.write(gospel.partition(" or ")[0])
          if firstReading:
              if weekcode.find("resurrection") * weekcode.find("pentecost1") * weekcode.find("pentecost2") == 0:
                  firstReading = firstReading.partition(" or ")[2]
                  secondReading = secondReading.partition(" or ")[2]
              with open (dest + "firstReading", "w") as t:
                  t.write(firstReading.partition(" or ")[0])
          if secondReading:
              with open (dest + "secondReading", "w") as t:
                  t.write(secondReading.partition(" or ")[0])

          # Start next line
          weekcode = f.readline().rstrip()
  print ("Parsed " + str(countRecords) + " records")
#+END_SRC

#+RESULTS:
: Parsed 85 records

** Produce Bible References for Yr B, Track 1 in =readings/refs/yearb/=
ISSUE: Already done by a different means. Not yet published into sharedprayers. Abandoning this effort.
Issues:
  - "Ecclesiaticus" collides with Ecclesiastes; use "Sirach" instead
  - someday track to could be added with alternate filenames
Create a directory for each week-code.
Name files =lesson1=, =lesson2=, =psalm=, =gospel=

#+BEGIN_SRC python :python python3 :results output
  import csv, os
  srcfile = "src/refs-ybt1.csv"
  targetdir = "output/readings/refs/yearb/"
  codeColumn = 1
  psalmColumn = 3
  lesson1Column= 4
  lesson2Column = 5
  gospelColumn = 6

  os.makedirs(targetdir, exist_ok=True)

  count=0
  with open(srcfile, "r") as f:
      reader = csv.reader(f)
      next(reader) # skip header line
      for row in reader:
          if row[codeColumn] == "": continue # Skip unused rows
          code = row[codeColumn].strip()
          gospel = ""
          if (row[gospelColumn]
          print (code[gospelColumn].strip())
          count+=1
  print ("Wrote " + str(count) + " records.")
#+END_SRC

#+RESULTS:

          with open (targetdir + "/" + code, "w") as t:
              t.write(row[introColumn])
** Produce Liturgies for 2020 (Yr B, Track 1) in =2020=
Issues:
- Ensure =/he/propercollect= excludes "The Lord be with you" on Good Friday
- Only produce liturgies for future dates
- Check / customize liturgies, Update bcppage for:
    o Good Friday (with special =he/propercollect=)
    o Palm Sunday
    o Easter Vigil
- o Modify contents pages to automatically provide next & previous service (based on liturgydate?)
-  o Access future/all services regardless of date?
- Next year:
    o Epiphany blessings protocol varies in year C
    o Replacement Passion Sunday scripts for C,A
    o Lectionaries for Year C, Year A
    o Year's worth of hymns?

#+BEGIN_SRC python :python python3 :results output
  import csv, os, datetime
  srcfile = "src/liturgy2021.csv"
  targetdir = "output/2021/"
  lectionaryyear = "yearb"

  dateOutputFormat = "%Y-%m-%d"
  dateColumn = 0
  i = 4
  codeColumn = 4
  titleColumn = 5
  prepareColumn = 6
  psalmStyleColumn = 12
  postscriptColumn = 32

  headings = {
    prepareColumn + 2 : "## We Gather in God's Name",
    psalmStyleColumn  : "## We Hear God's Word",
    psalmStyleColumn + 3 : "## We Respond in Faith",
    psalmStyleColumn + 8 : "## We Offer Ourselves To God",
    psalmStyleColumn + 13 : "## We Receive the Gift of God"
    }

  def shortcode(x):
      if x == "":
          return ""
      return '{{{{% {0} %}}}}\n'.format(x.strip())

  def shortcodeClosed(x):
      return shortcode(x).replace(" %}}", " /%}}")

  def shortcodeRow(x):
      return shortcode(row[x].strip())

  def shortcodeRowClosed(x):
      return shortcodeClosed(row[x].strip())

  os.makedirs(targetdir, exist_ok=True)

  count=0
  with open(srcfile, "r") as f:
      reader = csv.reader(f)
      next(reader) # skip header line
      for row in reader:
          if row[dateColumn] == "": continue # Skip unused rows
          code = row[codeColumn].strip()
          rowDate = datetime.datetime.strptime(row[dateColumn], '%m/%d/%y')
          if rowDate.date() < datetime.date.today(): continue # Skip past dates
          # print("DEBUG: Found date {0}".format(rowDate))
          liturgyDate = rowDate.strftime(dateOutputFormat)
          publishDate = (rowDate + datetime.timedelta(days=-6)).strftime(dateOutputFormat)
          filename = 'he-{0:%Y%m%d}-{1}.md'.format(rowDate, code)
          if (code == "goodfriday" or code == "holysaturday"):
              filename = '{0}-{1:%Y%m%d}.md'.format(code, rowDate)
          with open (targetdir + "/" + filename, "w") as t:
              t.write('---\n')
              if (code == "goodfriday" or code == "holysaturday"):
                  t.write('title: {}\n'.format(row[titleColumn].strip()))
              else:
                  t.write('title: Holy Eucharist, Rite II ({0})\n'.format(row[titleColumn].strip()))
              t.write('date: {0}\n'.format(publishDate))
              t.write('lectionaryyear: {0}\n'.format(lectionaryyear))
              t.write('proper: {0}\n'.format(code))
              t.write('liturgydate: {0}\n'.format(liturgyDate))
              t.write('bcppage: 355ff.\n')
              t.write('---\n')
              for i in range(prepareColumn + 1, postscriptColumn):
                  if (i == psalmStyleColumn):
                      t.write(shortcode('he/propercollect'))
                      t.write(shortcode('rubric-sit'))

                  if (headings.get(i)):
                      t.write('\n' + headings.get(i) + '\n')

                  if (i == psalmStyleColumn):
                      t.write(shortcodeClosed('he/lesson "firstReading"'))
                      t.write(shortcodeRowClosed(psalmStyleColumn))
                      t.write(shortcodeClosed('he/lesson "secondReading"'))
                      t.write(shortcodeClosed('he/gospel'))
                  else:
                      t.write(shortcodeRow(i))
          count+=1
  print ("Wrote " + str(count) + " records.")
#+END_SRC

#+RESULTS:
: Wrote 76 records.
